function val = Data_VertexEdgeGraphStruct()
	val = struct(...
		'state',						0,	...
		'numNodes',						0,	...		
		'nodeCoords',					[],	...
		'numEdges',						0,	...		
		'eNodMat',						[],	...
		'AssociatedVoxels',				[],	...
		'edgeLengths',					[]	...
	);
end